### ISSUE TITLE
Duplicate clause bug

### ISSUE THREAD

**Issue by JesseSilverberg** [mclumd/alma-2.0#3]
Running alma with these two statements, only one will end up in the knowledge base. If one of the `ros`s is changed to something else (`rosadsf`), they both show up.

`fif(and(hearing(julia),proc(learned(not(talking),A),bound)),conclusion(ros(speak()))).`
`fif(and(hearing(julia),proc(learned(not(talking),A),bound)),conclusion(ros(raise_arm()))).`

**Comment by goldburger** [comment]
Fixed in https://github.com/mclumd/alma-2.0/commit/41d9541275d83c5684f5e10c3dbaa9a658002100

**Comment by JesseSilverberg** [comment]
Still happens
